name: Validate PR

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  pr-check-workflow:
    uses: madLads-2k19/ci-cd-actions/.github/workflows/check-pr.yaml@master
    with:
      py-module: ango_auth
      python-version: 3.10.9
